qubes_hooks.py: consider transaction items only of some actions
Not all transaction items have associated package, consider only those
that do.

This fixes an error like this:

    Traceback (most recent call last):
      File "/usr/lib/python3.9/site-packages/dnf/plugin.py", line 104, in _caller
        getattr(plugin, method)()
      File "/usr/lib/python3.9/site-packages/dnf-plugins/qubes-hooks.py", line 78, in transaction
        updates.discard(item.pkg)
      File "/usr/lib/python3.9/site-packages/dnf/db/history.py", line 157, in pkg
        return self._swdb.rpm._swdb_ti_pkg[self._item]
    KeyError: <libdnf.transaction.TransactionItem; proxy of <Swig Object of type 'libdnf::TransactionItemPtr *' at 0x74ff5165c270> >

Exactly the same issue affected dnf itself: https://bugzilla.redhat.com/show_bug.cgi?id=1825213
The fix is copied from there.

Fixes QubesOS/qubes-issues#6993

(cherry picked from commit a8b22ac2d86deff2917263b16dd9ed3d4ed715e7)