qvm-features-request: gracefuly handle too long features
QubesDB path length limit doesn't allow full qrexec service name length.
This needs some better handling, but until that happens, let it handle
more gracefuly than python traceback like this:

Traceback (most recent call last):
  File "/usr/bin/qvm-features-request", line 88, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/bin/qvm-features-request", line 79, in main
    qdb.write('/features-request/' + feature, value)
qubesdb.Error: (0, 'Error')

Fixes QubesOS/qubes-issues#8609

(cherry picked from commit 572c5f19a9fa4f5ddf710c46b5fabac96e773242)